[package]
name = "model"
version = "0.1.0"
authors = ["Sebastian Schmidt <isibboi@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
custom_derive = "0.1"
enum_derive = "0.1"
failure = "0.1"

[dev-dependencies]
rand = "0.6"