[package]
name = "marketsim"
version = "0.1.0"
authors = ["Sebastian Schmidt <isibboi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
log = "0.4"
simplelog = "0.5"
rand = "0.7"
derive-new = "0.5"